name: Docker Compose Build and Test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Environment
        run: |
          cp ./taskmaster/.env.example ./taskmaster/.env

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d

      - name: Check MySQL Socket
        run: |
          docker exec taskmaster_db chmod -R 777 /var/run/mysqld/
          docker exec taskmaster_db bash -c 'ls -l /var/run/mysqld/'

      - name: Test db connection
        run: |
          docker-compose ps -a
          docker-compose exec taskmaster_db bash -c "mysql -u root -ppassword -e 'show tables;'"

      - name: Run migrations
        run: |
          docker compose exec laravel_app bash -c "php artisan migrate:fresh --seed"

      - name: Run tests
        run: |
          docker compose exec laravel_app bash -c "php artisan test"
