name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Docker Compose
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged
        ports:
          - 8081:8081
          - 8000:80
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: taskmaster
          MYSQL_USER: root
          VITE_APP_API_URL: http://laravel_app

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          sleep 30 # adjust time as needed for containers to start

      - name: Check containers are up and running
        run: docker ps -a

      - name: Run Laravel migrations
        run: docker exec laravel_app php artisan migrate --force

      - name: Run Laravel tests
        run: docker exec laravel_app php artisan test

      - name: Front End can call a curl to the Back End
        run: |
          docker compose exec vue3_spa curl http://laravel_app/api/test
          docker compose exec vue3_spa curl -X POST -d "email=task@taskmaster.test&password=password" http://laravel_app/api/test

      - name: Run e2e tests
        run: docker exec vue3_spa pnpm cypress:run
